pub struct InternalAddressToCreateModel {
    pub department: Option<String>,
    pub sub_department: Option<String>,
    pub floor: Option<String>,
    pub room: Option<String>,
    pub building_name: Option<String>,
    pub street_name: String,
    pub building_number: Option<String>,
    pub post_box: Option<String>,
    pub town_location_name: Option<String>,
    pub post_code: String,
    pub town_name: String,
    pub district_name: Option<String>,
    pub country_subdivision: Option<String>,
    pub country: String,
}
